[package]
name = "bevy_event_modifiers"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = { version = "0.14", default-features = false }
bevy_ecs = { version = "0.14", default-features = false }