[package]
name = "bevy_event_modifiers"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_event_modifiers_macros = { path = "../bevy_event_modifiers_macros" }
